### ISSUE TITLE
Remove dependency on /3ds/StarUpdater directory

### ISSUE THREAD

**Issue by gnmmarechal** [gnmmarechal/StarUpdater-UN#1]
And replace it with the already used /StarUpdater directory, I suppose.

**Comment by Margen67** [comment]
It should be moved to 3ds/data to reduce SD card root clutter

**Comment by gnmmarechal** [comment]
I don't agree with that. I could make the directory specified on the makefile, though, if someone wants a different dir, they would only need to compile it with that changed.

**Comment by gnmmarechal** [comment]
Uh. I might not even bother changing it to set it through the Makefile, I mean, the working dir is the first variable to be set in the script.

**Comment by favna** [comment]
/StarUpdater is not a required directory at all. I can run StarUpdater-UN just fine without that directory.

**Comment by gnmmarechal** [comment]
Unless you're using an old version (or unless I made this change after the last release, I don't remember), /StarUpdater is used for downloads. Not sure if I've already set backups to go on there. I don't think I have, tbh. Haven't had much time to work on this. The directory is supposed to be used by more stuff, and StarUpdater-UN creates it.

**Comment by favna** [comment]
Well in that case yes please do move it to /3ds/data/StarUpdater-UN like Margen said. Root clutter is extremely frowned upon in the community and won't attract people to your tool.

**Comment by Margen67** [comment]
https://github.com/gnmmarechal/StarUpdater-UN/pull/4

**Comment by gnmmarechal** [comment]
I dislike the /3ds/data directory.

Not to mention, clutter isn't "extremely frowned upon in the community". There is a large number of people who don't care. and those that like the directories at the root of the SD also exist. 

I may change it at some point, and maybe to that directory, but it's not a priority.

**Comment by Margen67** [comment]
>I dislike the /3ds/data directory.

Why?

It makes the most sense for what it's doing, reduces SD root clutter.

>There is a large number of people who don't care. and those that like the directories at the root of the SD also exist.

It's an easy change so I don't see why it's a big deal.

I've never heard of people that actually _prefer_ SD root clutter.

**Comment by pbanj** [comment]
Could just use the /luma directory.

**Comment by Margen67** [comment]
Continued in https://github.com/gnmmarechal/StarUpdater-UN/issues/5
