### ISSUE TITLE
Update path changer function

### ISSUE THREAD

**Issue by gnmmarechal** [gnmmarechal/StarUpdater-UN#2]
It still uses the old method to patch the path for the payload. That is no longer required, and can be replaced with a simple config file copy to the /luma directory.

**Comment by Margen67** [comment]
Would it be possible to make it so the payload is put on CTRNAND?

**Comment by gnmmarechal** [comment]
Unfortunately not, LPP cannot write to CTRNAND. That's not a big problem though. Especially considering that SD payload is checked first. I don't really like the idea of writing to the NAND all the time just to update the payload.

**Comment by gnmmarechal** [comment]
https://github.com/gnmmarechal/StarUpdater-UN/commit/1a6cb1c0b31cc0d08c6918eb7449977000cdbccb
