### ISSUE TITLE
Put payload onto CTRNAND

### ISSUE THREAD

**Issue by Margen67** [gnmmarechal/StarUpdater-UN#3]
As of https://github.com/gnmmarechal/StarUpdater-UN/commit/ff54ca68dd0e0e9759e4bfc77e1f4c1c111b9cb2 you can download a payload to the SD but not to NAND.

It would be nice to not have to manually use FBI to copy+paste+delete the payload each there's an update.

**Comment by gnmmarechal** [comment]
Not possible, LPP-3DS cannot do this.
Also, I'm pretty sure prior to that commit of SU-UN, it wasn't possible to do so anyway.
